import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { makeStyles, createStyles, Theme } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';

const getContext = require.context(
  '',//pages
  true,
  /context\.(tsx|js)$/
)

export const ListComponents = getContext.keys().map((dir: string) => {
  console.log('pages/index', dir)
  return getContext(dir).default as React.FunctionComponent<any>
})


const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      '& > *': {
        margin: theme.spacing(1),
      },
    },
  }),
);

export default function Home() {
  const classes = useStyles()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div> list:{
        ListComponents
          .map(
            (Component, index) => {
              return <Component key={index} />
            }
          )
      }
      </div>

      <Link href="/login">
        <a>Login</a>
      </Link>
      <Link href="/userNew">
        <a>New User</a>
      </Link>
    </div>
  )
}
